### ISSUE TITLE
refused to compile?

### ISSUE THREAD

**Issue by Ayabara1013** [sefinek24/random-cat-img#17]
here is the error

node:https
Module build failed: UnhandledSchemeError: Reading from "node:https" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

**Comment by sefinek** [comment]
What is your node.js version?
https://nodejs.org/api/esm.html#node-imports
